"""update commenttable 

Revision ID: 121063ccf6c3
Revises: 3b84c60b1881
Create Date: 2019-11-24 15:36:35.587387

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '121063ccf6c3'
down_revision = '3b84c60b1881'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('commenttable', sa.Column('pitchID', sa.Integer(), nullable=True))
    op.drop_constraint('commenttable_pitch_fkey', 'commenttable', type_='foreignkey')
    op.create_foreign_key(None, 'commenttable', 'pitchtable', ['pitchID'], ['id'])
    op.drop_column('commenttable', 'pitch')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('commenttable', sa.Column('pitch', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'commenttable', type_='foreignkey')
    op.create_foreign_key('commenttable_pitch_fkey', 'commenttable', 'pitchtable', ['pitch'], ['id'])
    op.drop_column('commenttable', 'pitchID')
    # ### end Alembic commands ###
