"""update commenttable 

Revision ID: 3b84c60b1881
Revises: ab414ad3c9fe
Create Date: 2019-11-24 01:38:17.904435

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b84c60b1881'
down_revision = 'ab414ad3c9fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('commenttable', sa.Column('pitch', sa.Integer(), nullable=True))
    op.drop_constraint('commenttable_pitch_id_fkey', 'commenttable', type_='foreignkey')
    op.create_foreign_key(None, 'commenttable', 'pitchtable', ['pitch'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'commenttable', type_='foreignkey')
    op.create_foreign_key('commenttable_pitch_id_fkey', 'commenttable', 'pitchtable', ['pitch_id'], ['id'])
    op.drop_column('commenttable', 'pitch')
    # ### end Alembic commands ###
