"""add column to pitch table

Revision ID: b5e5ae8b9a6d
Revises: 58951df819e3
Create Date: 2019-11-23 23:39:30.268657

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5e5ae8b9a6d'
down_revision = '58951df819e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'commenttable', 'pitchtable', ['pitch_id'], ['id'])
    op.add_column('pitchtable', sa.Column('username', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pitchtable', 'username')
    op.drop_constraint(None, 'commenttable', type_='foreignkey')
    # ### end Alembic commands ###
