"""change username column  to poster_name 

Revision ID: e42bb70ee140
Revises: b5e5ae8b9a6d
Create Date: 2019-11-23 23:50:24.186593

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e42bb70ee140'
down_revision = 'b5e5ae8b9a6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitchtable', sa.Column('poster_name', sa.String(), nullable=True))
    op.drop_column('pitchtable', 'username')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitchtable', sa.Column('username', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.drop_column('pitchtable', 'poster_name')
    # ### end Alembic commands ###
