"""update path to profile pic

Revision ID: f078da3d144b
Revises: fb26ee07c16f
Create Date: 2019-11-23 13:38:32.537382

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f078da3d144b'
down_revision = 'fb26ee07c16f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_usertable_username'), 'usertable', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usertable_username'), table_name='usertable')
    # ### end Alembic commands ###
